'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import "./styles/layout.css";
import CompanyItem from "./components/CompanyItem";
import { useEffect, useState } from "react";
import { Company } from "./models/Company";
import CompanyService from "./services/CompanyService";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [companies, setCompanies] = useState<Array<Company>>([]);

  useEffect(() => {
    CompanyService.list()
      .then((response) => {
        setCompanies(response.data)
      })
      .catch((error) => {
        console.log('Something is wrong', error.response.data)
      })
  }, [])

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="main-header p-3">
          <div className="grid grid-cols-2 items-center">
            <img src="/imgs/logo.svg" alt="Tractian" />

            <nav className="text-right">
              { companies.map((company: Company) => <CompanyItem key={company.id} company={company} onClick={(e) => {
                e.preventDefault()

                console.log('oi');
              }} />) }
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
